version: '3.8'

services:
  postgress:
    image: postgres:15
    container_name: school
    environment:
      POSTGRES_USER: nsa
      POSTGRES_PASSWORD: nsa
      POSTGRES_DB: school
    ports:
      - '4444:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  app:
    build: .
    container_name: nextjs_app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL: postgresql://nsa:nsa@localhost:4444/school
    depends_on:
      - postgres

volumes:
  postgres_data: